export const CHANGE_PASSWORD  = 'CHANGE_PASSWORD '
export const SIGN_IN_POST = 'SIGN_IN_POST'
export const CHANGE_PASSWORD_SEND = 'CHANGE_PASSWORD_SEND'
export const GET_AUTH = 'GET_AUTH'
export const SHOW_LOADER = 'GET_AUTH'
export const HIDE_LOADER= 'GET_AUTH'
export const HIDE_PRELOADER= 'HIDE_PRELOADER'
export const SHOW_PRELOADER= 'SHOW_PRELOADER'
export const GET_USERS= 'GET_USERS'
export const ADD_TECHNICIAN = 'ADD_TECHNICIAN'
export const GET_ACTIVITY_MAP = 'GET_ACTIVITY_MAP'



